### ISSUE TITLE
Floating Point Literals do not always work as expected

### ISSUE THREAD

**Issue by mgriebling** [Zollerboy1/BigDecimal#1]
Just a heads up that the following test case shows that floating point literals (in Swift) do not work correctly with Decimal numbers. (They get rounded into binary floating point by the compiler).  I am trying to get this fixed but just wanted everyone to be aware.   Here's a test case:

```Swift
  func testNumericLiterals() throws {
    let xStr = BigDecimal("1.333333333333333333")!
    let yStr = BigDecimal("1.333333333333333334")!
    print(xStr == yStr) // false

    let xDbl: BigDecimal = 1.333333333333333333
    let yDbl: BigDecimal = 1.333333333333333334
    print(xDbl == yDbl) // true
  }
```

**Comment by Zollerboy1** [comment]
Yeah, I'm aware of this issue. I still thought that it makes sense to support floating point literals, as you can still initialize `BigDecimal` correctly with one, as long as you don't use more than 15 digits of precision.

Still, it isn't an ideal situation, so I'm very glad that you're pushing this issue forward over on Swift Evolution!
